def test_nav(mkdocs, logs):
    mkdocs.files(
        """
        docs/
            foo.md
        mkdocs.yml
        | site_name: Test
        | plugins:
        |   - awesome-nav
        | nav:
        |   - Title: foo.md
        """
    )
    mkdocs.build().assert_nav(
        """
        - Foo: foo.md
        """
    )
    assert logs.from_plugin == [
        logs.warning("awesome-nav: 'nav' config from mkdocs.yml is being replaced with one generated by awesome-nav")
    ]


def test_not_in_nav(mkdocs):
    mkdocs.files(
        """
        docs/
            foo.md
            bar.md
        mkdocs.yml
        | site_name: Test
        | plugins:
        |   - awesome-nav
        | not_in_nav: /foo.md
        """
    )
    mkdocs.build().assert_nav(
        """
        - Bar: bar.md
        """
    )


def test_exclude_docs(mkdocs):
    mkdocs.files(
        """
        docs/
            foo.md
            bar.md
        mkdocs.yml
        | site_name: Test
        | plugins:
        |   - awesome-nav
        | exclude_docs: /foo.md
        """
    )
    mkdocs.build().assert_nav(
        """
        - Bar: bar.md
        """
    )
